service: python-demo-service
description: Sample knative service
provider:
  name: triggermesh
functions:
  python-function:
    source: handler.py
    runtime: https://raw.githubusercontent.com/triggermesh/knative-lambda-runtime/master/python37/runtime.yaml
    buildargs:
    - HANDLER=handler.endpoint
    environment:
      EVENT: API_GATEWAY
      foo: bar
